// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Transit.Infrastructure.Persistence;

#nullable disable

namespace Transit.Infrastructure.Migrations
{
    [DbContext(typeof(TransitDbContext))]
    [Migration("20260512201526_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Pasazerowie.BiletyOkresowe", b =>
                {
                    b.Property<int>("IdBiletu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_biletu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBiletu"));

                    b.Property<bool>("Aktywny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("aktywny");

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("cena");

                    b.Property<DateOnly>("DataDo")
                        .HasColumnType("date")
                        .HasColumnName("data_do");

                    b.Property<DateOnly>("DataOd")
                        .HasColumnType("date")
                        .HasColumnName("data_od");

                    b.Property<int>("IdKategorii")
                        .HasColumnType("integer")
                        .HasColumnName("id_kategorii");

                    b.Property<int>("IdPasazera")
                        .HasColumnType("integer")
                        .HasColumnName("id_pasazera");

                    b.HasKey("IdBiletu");

                    b.HasIndex("IdKategorii");

                    b.HasIndex("IdPasazera");

                    b.ToTable("Bilety_Okresowe", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Pasazerowie.KontrolaWPojedzie", b =>
                {
                    b.Property<int>("IdKontroli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_kontroli");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdKontroli"));

                    b.Property<DateTime>("DataGodzina")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_godzina");

                    b.Property<int>("IdKontrolera")
                        .HasColumnType("integer")
                        .HasColumnName("id_kontrolera");

                    b.Property<int>("IdRealizacji")
                        .HasColumnType("integer")
                        .HasColumnName("id_realizacji");

                    b.Property<string>("Wynik")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("wynik");

                    b.HasKey("IdKontroli");

                    b.HasIndex("IdKontrolera");

                    b.HasIndex("IdRealizacji");

                    b.ToTable("Kontrole_W_Pojazdach", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Pasazerowie.Mandat", b =>
                {
                    b.Property<int>("IdMandatu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_mandatu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMandatu"));

                    b.Property<DateOnly?>("DataPlatnosci")
                        .HasColumnType("date")
                        .HasColumnName("data_platnosci");

                    b.Property<int>("IdKontroli")
                        .HasColumnType("integer")
                        .HasColumnName("id_kontroli");

                    b.Property<int?>("IdPasazera")
                        .HasColumnType("integer")
                        .HasColumnName("id_pasazera");

                    b.Property<decimal>("Kwota")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("kwota");

                    b.Property<string>("NrDokumentuPasazera")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nr_dokumentu_pasazera");

                    b.Property<bool>("Oplacony")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("oplacony");

                    b.Property<string>("Powod")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("powod");

                    b.HasKey("IdMandatu");

                    b.HasIndex("IdKontroli");

                    b.HasIndex("IdPasazera");

                    b.ToTable("Mandaty", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Pasazerowie.Pasazer", b =>
                {
                    b.Property<int>("IdPasazera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pasazera");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPasazera"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("imie");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nazwisko");

                    b.Property<string>("Pesel")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("pesel");

                    b.HasKey("IdPasazera");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("Pesel")
                        .IsUnique()
                        .HasFilter("pesel IS NOT NULL");

                    b.ToTable("Pasazerowie", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Personel.BadanieLekarskie", b =>
                {
                    b.Property<int>("IdBadania")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_badania");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBadania"));

                    b.Property<DateOnly>("DataBadania")
                        .HasColumnType("date")
                        .HasColumnName("data_badania");

                    b.Property<DateOnly>("DataWaznosci")
                        .HasColumnType("date")
                        .HasColumnName("data_waznosci");

                    b.Property<int>("IdKierowcy")
                        .HasColumnType("integer")
                        .HasColumnName("id_kierowcy");

                    b.Property<string>("Lekarz")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lekarz");

                    b.Property<string>("Wynik")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("wynik");

                    b.HasKey("IdBadania");

                    b.HasIndex("IdKierowcy");

                    b.ToTable("Badania_Lekarskie", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Personel.Kierowca", b =>
                {
                    b.Property<int>("IdKierowcy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_kierowcy");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdKierowcy"));

                    b.Property<bool>("Aktywny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("aktywny");

                    b.Property<DateOnly>("DataZatrudnienia")
                        .HasColumnType("date")
                        .HasColumnName("data_zatrudnienia");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("imie");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nazwisko");

                    b.Property<string>("NrPracownika")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nr_pracownika");

                    b.HasKey("IdKierowcy");

                    b.HasIndex("NrPracownika")
                        .IsUnique();

                    b.ToTable("Kierowcy", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Personel.Kontroler", b =>
                {
                    b.Property<int>("IdKontrolera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_kontrolera");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdKontrolera"));

                    b.Property<bool>("Aktywny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("aktywny");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("imie");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nazwisko");

                    b.Property<string>("NrSluzbowy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nr_sluzbowy");

                    b.HasKey("IdKontrolera");

                    b.HasIndex("NrSluzbowy")
                        .IsUnique();

                    b.ToTable("Kontrolerzy", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Personel.UprawnienieKierowcy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataUzyskania")
                        .HasColumnType("date")
                        .HasColumnName("data_uzyskania");

                    b.Property<DateOnly>("DataWaznosci")
                        .HasColumnType("date")
                        .HasColumnName("data_waznosci");

                    b.Property<int>("IdKierowcy")
                        .HasColumnType("integer")
                        .HasColumnName("id_kierowcy");

                    b.Property<int>("IdUprawnienia")
                        .HasColumnType("integer")
                        .HasColumnName("id_uprawnienia");

                    b.HasKey("Id");

                    b.HasIndex("IdKierowcy");

                    b.HasIndex("IdUprawnienia");

                    b.ToTable("Uprawnienia_Kierowcow", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Pojazdy.ModelPojazdu", b =>
                {
                    b.Property<int>("IdModelu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_modelu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdModelu"));

                    b.Property<int>("IdProducenta")
                        .HasColumnType("integer")
                        .HasColumnName("id_producenta");

                    b.Property<int>("LiczbaMiejsc")
                        .HasColumnType("integer")
                        .HasColumnName("liczba_miejsc");

                    b.Property<string>("NazwaModelu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nazwa_modelu");

                    b.Property<string>("TypPojazdu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("typ_pojazdu");

                    b.HasKey("IdModelu");

                    b.HasIndex("IdProducenta");

                    b.ToTable("Modele_Pojazdow", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Pojazdy.Pojazd", b =>
                {
                    b.Property<int>("IdPojazdu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pojazdu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPojazdu"));

                    b.Property<bool>("Aktywny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("aktywny");

                    b.Property<DateOnly>("DataZakupu")
                        .HasColumnType("date")
                        .HasColumnName("data_zakupu");

                    b.Property<int>("IdModelu")
                        .HasColumnType("integer")
                        .HasColumnName("id_modelu");

                    b.Property<string>("NumerBoczny")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numer_boczny");

                    b.Property<int>("RokProdukcji")
                        .HasColumnType("integer")
                        .HasColumnName("rok_produkcji");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("vin");

                    b.HasKey("IdPojazdu");

                    b.HasIndex("IdModelu");

                    b.HasIndex("NumerBoczny")
                        .IsUnique();

                    b.HasIndex("Vin")
                        .IsUnique();

                    b.ToTable("Pojazdy", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Pojazdy.ProducentPojazdu", b =>
                {
                    b.Property<int>("IdProducenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_producenta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProducenta"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nazwa");

                    b.HasKey("IdProducenta");

                    b.HasIndex("Nazwa")
                        .IsUnique();

                    b.ToTable("Producenci_Pojazdow", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Rozklady.DziennikPrzejazdu", b =>
                {
                    b.Property<int>("IdWpisu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_wpisu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdWpisu"));

                    b.Property<int>("IdOdjazdu")
                        .HasColumnType("integer")
                        .HasColumnName("id_odjazdu");

                    b.Property<int>("IdRealizacji")
                        .HasColumnType("integer")
                        .HasColumnName("id_realizacji");

                    b.Property<short>("OffsetDni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("offset_dni");

                    b.Property<int?>("OpoznienieMin")
                        .HasColumnType("integer")
                        .HasColumnName("opoznienie_min");

                    b.Property<DateTime?>("RzeczywiistyOdjazd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rzeczywisty_odjazd");

                    b.Property<DateTime?>("RzeczywiistyPrzyjazd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rzeczywisty_przyjazd");

                    b.HasKey("IdWpisu");

                    b.HasIndex("IdOdjazdu");

                    b.HasIndex("IdRealizacji");

                    b.ToTable("Dziennik_Przejazdu", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Rozklady.GrafikPracy", b =>
                {
                    b.Property<int>("IdGrafiku")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_grafiku");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGrafiku"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<TimeOnly>("GodzinaDo")
                        .HasColumnType("time")
                        .HasColumnName("godzina_do");

                    b.Property<TimeOnly>("GodzinaOd")
                        .HasColumnType("time")
                        .HasColumnName("godzina_od");

                    b.Property<int>("IdKierowcy")
                        .HasColumnType("integer")
                        .HasColumnName("id_kierowcy");

                    b.Property<int>("IdPojazdu")
                        .HasColumnType("integer")
                        .HasColumnName("id_pojazdu");

                    b.Property<short>("OffsetDni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("offset_dni");

                    b.HasKey("IdGrafiku");

                    b.HasIndex("IdKierowcy");

                    b.HasIndex("IdPojazdu");

                    b.ToTable("Grafiki_Pracy", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Rozklady.OdjazdPlanowy", b =>
                {
                    b.Property<int>("IdOdjazdu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_odjazdu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOdjazdu"));

                    b.Property<int>("IdPrzystankuWariantu")
                        .HasColumnType("integer")
                        .HasColumnName("id_przystanku_wariantu");

                    b.Property<int>("IdRozkladu")
                        .HasColumnType("integer")
                        .HasColumnName("id_rozkladu");

                    b.Property<int>("NrKursu")
                        .HasColumnType("integer")
                        .HasColumnName("nr_kursu");

                    b.Property<short>("OffsetDni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("offset_dni");

                    b.Property<TimeOnly>("PlanowaGodzinaOdjazdu")
                        .HasColumnType("time")
                        .HasColumnName("planowa_godzina_odjazdu");

                    b.HasKey("IdOdjazdu");

                    b.HasIndex("IdPrzystankuWariantu");

                    b.HasIndex("IdRozkladu", "IdPrzystankuWariantu");

                    b.ToTable("Odjazdy_Planowe", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Rozklady.PrzegladUsterka", b =>
                {
                    b.Property<int>("IdPrzegladu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_przegladu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPrzegladu"));

                    b.Property<DateOnly>("DataPrzegladu")
                        .HasColumnType("date")
                        .HasColumnName("data_przegladu");

                    b.Property<int>("IdPojazdu")
                        .HasColumnType("integer")
                        .HasColumnName("id_pojazdu");

                    b.Property<int>("IdTypuPrzegladu")
                        .HasColumnType("integer")
                        .HasColumnName("id_typu_przegladu");

                    b.Property<string>("Uwagi")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("uwagi");

                    b.Property<string>("Warsztat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("warsztat");

                    b.Property<string>("Wynik")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("wynik");

                    b.HasKey("IdPrzegladu");

                    b.HasIndex("IdPojazdu");

                    b.HasIndex("IdTypuPrzegladu");

                    b.ToTable("Przeglady_Usterki", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Rozklady.RealizacjaKursu", b =>
                {
                    b.Property<int>("IdRealizacji")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_realizacji");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRealizacji"));

                    b.Property<DateOnly>("DataKursu")
                        .HasColumnType("date")
                        .HasColumnName("data_kursu");

                    b.Property<int?>("IdKierowcy")
                        .HasColumnType("integer")
                        .HasColumnName("id_kierowcy");

                    b.Property<int?>("IdPojazdu")
                        .HasColumnType("integer")
                        .HasColumnName("id_pojazdu");

                    b.Property<int>("IdWariantu")
                        .HasColumnType("integer")
                        .HasColumnName("id_wariantu");

                    b.Property<int>("NrKursu")
                        .HasColumnType("integer")
                        .HasColumnName("nr_kursu");

                    b.Property<string>("StatusKursu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_kursu");

                    b.HasKey("IdRealizacji");

                    b.HasIndex("IdKierowcy");

                    b.HasIndex("IdPojazdu");

                    b.HasIndex("IdWariantu", "DataKursu", "NrKursu")
                        .IsUnique();

                    b.ToTable("Realizacja_Kursu", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Rozklady.RozkladJazdy", b =>
                {
                    b.Property<int>("IdRozkladu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rozkladu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRozkladu"));

                    b.Property<bool>("Aktywny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("aktywny");

                    b.Property<DateOnly?>("DataWaznosciDo")
                        .HasColumnType("date")
                        .HasColumnName("data_waznosci_do");

                    b.Property<DateOnly>("DataWaznosciOd")
                        .HasColumnType("date")
                        .HasColumnName("data_waznosci_od");

                    b.Property<int>("IdTypuDnia")
                        .HasColumnType("integer")
                        .HasColumnName("id_typu_dnia");

                    b.Property<int>("IdWariantu")
                        .HasColumnType("integer")
                        .HasColumnName("id_wariantu");

                    b.HasKey("IdRozkladu");

                    b.HasIndex("IdTypuDnia");

                    b.HasIndex("IdWariantu");

                    b.ToTable("Rozklady_Jazdy", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Siec.Linia", b =>
                {
                    b.Property<int>("IdLinii")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_linii");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLinii"));

                    b.Property<bool>("Aktywna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("aktywna");

                    b.Property<string>("NumerLinii")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numer_linii");

                    b.Property<string>("Opis")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("opis");

                    b.Property<string>("TypLinii")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("typ_linii");

                    b.HasKey("IdLinii");

                    b.HasIndex("NumerLinii")
                        .IsUnique();

                    b.ToTable("Linie", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Siec.Przystanek", b =>
                {
                    b.Property<int>("IdPrzystanku")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_przystanku");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPrzystanku"));

                    b.Property<bool>("Aktywny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("aktywny");

                    b.Property<int>("IdDzielnicy")
                        .HasColumnType("integer")
                        .HasColumnName("id_dzielnicy");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nazwa");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("naziemny")
                        .HasColumnName("typ");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ulica");

                    b.Property<bool>("Wiata")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("wiata");

                    b.HasKey("IdPrzystanku");

                    b.HasIndex("IdDzielnicy");

                    b.ToTable("Przystanki", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Siec.PrzystanekWariantu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPrzystanku")
                        .HasColumnType("integer")
                        .HasColumnName("id_przystanku");

                    b.Property<int>("IdWariantu")
                        .HasColumnType("integer")
                        .HasColumnName("id_wariantu");

                    b.Property<int>("Kolejnosc")
                        .HasColumnType("integer")
                        .HasColumnName("kolejnosc");

                    b.Property<int>("OdlegloscOdPoczatkuM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("odleglosc_od_poczatku_m");

                    b.HasKey("Id");

                    b.HasIndex("IdPrzystanku");

                    b.HasIndex("IdWariantu", "IdPrzystanku")
                        .IsUnique();

                    b.HasIndex("IdWariantu", "Kolejnosc")
                        .IsUnique();

                    b.ToTable("Przystanki_Wariantu", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Siec.WariantTrasy", b =>
                {
                    b.Property<int>("IdWariantu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_wariantu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdWariantu"));

                    b.Property<bool>("Aktywny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("aktywny");

                    b.Property<int>("IdLinii")
                        .HasColumnType("integer")
                        .HasColumnName("id_linii");

                    b.Property<string>("Kierunek")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("kierunek");

                    b.Property<string>("NazwaWariantu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nazwa_wariantu");

                    b.HasKey("IdWariantu");

                    b.HasIndex("IdLinii", "NazwaWariantu")
                        .IsUnique();

                    b.ToTable("Warianty_Trasy", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Slowniki.Dzielnica", b =>
                {
                    b.Property<int>("IdDzielnicy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_dzielnicy");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDzielnicy"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nazwa");

                    b.HasKey("IdDzielnicy");

                    b.HasIndex("Nazwa")
                        .IsUnique();

                    b.ToTable("Dzielnice", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Slowniki.KategoriaOplaty", b =>
                {
                    b.Property<int>("IdKategorii")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_kategorii");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdKategorii"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nazwa");

                    b.Property<int>("ZnizkaPct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("znizka_pct");

                    b.HasKey("IdKategorii");

                    b.HasIndex("Nazwa")
                        .IsUnique();

                    b.ToTable("Kategorie_Biletow", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Slowniki.TypDnia", b =>
                {
                    b.Property<int>("IdTypuDnia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_typu_dnia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypuDnia"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("kod");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nazwa");

                    b.HasKey("IdTypuDnia");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Typy_Dni", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Slowniki.TypPrzegladu", b =>
                {
                    b.Property<int>("IdTypuPrzegladu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_typu_przegladu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypuPrzegladu"));

                    b.Property<int>("InterwalDni")
                        .HasColumnType("integer")
                        .HasColumnName("interwal_dni");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("kod");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nazwa");

                    b.HasKey("IdTypuPrzegladu");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Typy_Przegladu", (string)null);
                });

            modelBuilder.Entity("Transit.Domain.Entities.Slowniki.UprawnienieKategorii", b =>
                {
                    b.Property<int>("IdUprawnienia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_uprawnienia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUprawnienia"));

                    b.Property<string>("Kategoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kategoria");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("opis");

                    b.HasKey("IdUprawnienia");

                    b.HasIndex("Kategoria")
                        .IsUnique();

                    b.ToTable("Uprawnienia_Kategorii", (string)null);
                });

            modelBuilder.Entity("Transit.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Transit.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Transit.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Transit.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Transit.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Transit.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transit.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Transit.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Transit.Domain.Entities.Pasazerowie.BiletyOkresowe", b =>
                {
                    b.HasOne("Transit.Domain.Entities.Slowniki.KategoriaOplaty", "Kategoria")
                        .WithMany("Bilety")
                        .HasForeignKey("IdKategorii")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transit.Domain.Entities.Pasazerowie.Pasazer", "Pasazer")
                        .WithMany("Bilety")
                        .HasForeignKey("IdPasazera")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategoria");

                    b.Navigation("Pasazer");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Pasazerowie.KontrolaWPojedzie", b =>
                {
                    b.HasOne("Transit.Domain.Entities.Personel.Kontroler", "Kontroler")
                        .WithMany("Kontrole")
                        .HasForeignKey("IdKontrolera")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transit.Domain.Entities.Rozklady.RealizacjaKursu", "Realizacja")
                        .WithMany("Kontrole")
                        .HasForeignKey("IdRealizacji")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kontroler");

                    b.Navigation("Realizacja");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Pasazerowie.Mandat", b =>
                {
                    b.HasOne("Transit.Domain.Entities.Pasazerowie.KontrolaWPojedzie", "Kontrola")
                        .WithMany("Mandaty")
                        .HasForeignKey("IdKontroli")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transit.Domain.Entities.Pasazerowie.Pasazer", "Pasazer")
                        .WithMany("Mandaty")
                        .HasForeignKey("IdPasazera");

                    b.Navigation("Kontrola");

                    b.Navigation("Pasazer");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Personel.BadanieLekarskie", b =>
                {
                    b.HasOne("Transit.Domain.Entities.Personel.Kierowca", "Kierowca")
                        .WithMany("Badania")
                        .HasForeignKey("IdKierowcy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kierowca");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Personel.UprawnienieKierowcy", b =>
                {
                    b.HasOne("Transit.Domain.Entities.Personel.Kierowca", "Kierowca")
                        .WithMany("Uprawnienia")
                        .HasForeignKey("IdKierowcy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transit.Domain.Entities.Slowniki.UprawnienieKategorii", "UprawnienieKategorii")
                        .WithMany("UprawnieniKierowcow")
                        .HasForeignKey("IdUprawnienia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kierowca");

                    b.Navigation("UprawnienieKategorii");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Pojazdy.ModelPojazdu", b =>
                {
                    b.HasOne("Transit.Domain.Entities.Pojazdy.ProducentPojazdu", "Producent")
                        .WithMany("Modele")
                        .HasForeignKey("IdProducenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producent");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Pojazdy.Pojazd", b =>
                {
                    b.HasOne("Transit.Domain.Entities.Pojazdy.ModelPojazdu", "Model")
                        .WithMany("Pojazdy")
                        .HasForeignKey("IdModelu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Rozklady.DziennikPrzejazdu", b =>
                {
                    b.HasOne("Transit.Domain.Entities.Rozklady.OdjazdPlanowy", "Odjazd")
                        .WithMany("Dzienniki")
                        .HasForeignKey("IdOdjazdu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transit.Domain.Entities.Rozklady.RealizacjaKursu", "Realizacja")
                        .WithMany("Dzienniki")
                        .HasForeignKey("IdRealizacji")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Odjazd");

                    b.Navigation("Realizacja");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Rozklady.GrafikPracy", b =>
                {
                    b.HasOne("Transit.Domain.Entities.Personel.Kierowca", "Kierowca")
                        .WithMany("Grafiki")
                        .HasForeignKey("IdKierowcy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transit.Domain.Entities.Pojazdy.Pojazd", "Pojazd")
                        .WithMany("Grafiki")
                        .HasForeignKey("IdPojazdu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kierowca");

                    b.Navigation("Pojazd");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Rozklady.OdjazdPlanowy", b =>
                {
                    b.HasOne("Transit.Domain.Entities.Siec.PrzystanekWariantu", "PrzystanekWariantu")
                        .WithMany("Odjazdy")
                        .HasForeignKey("IdPrzystankuWariantu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transit.Domain.Entities.Rozklady.RozkladJazdy", "Rozklad")
                        .WithMany("Odjazdy")
                        .HasForeignKey("IdRozkladu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrzystanekWariantu");

                    b.Navigation("Rozklad");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Rozklady.PrzegladUsterka", b =>
                {
                    b.HasOne("Transit.Domain.Entities.Pojazdy.Pojazd", "Pojazd")
                        .WithMany("Przeglady")
                        .HasForeignKey("IdPojazdu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transit.Domain.Entities.Slowniki.TypPrzegladu", "TypPrzegladu")
                        .WithMany("Przeglady")
                        .HasForeignKey("IdTypuPrzegladu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pojazd");

                    b.Navigation("TypPrzegladu");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Rozklady.RealizacjaKursu", b =>
                {
                    b.HasOne("Transit.Domain.Entities.Personel.Kierowca", "Kierowca")
                        .WithMany("Realizacje")
                        .HasForeignKey("IdKierowcy");

                    b.HasOne("Transit.Domain.Entities.Pojazdy.Pojazd", "Pojazd")
                        .WithMany("Realizacje")
                        .HasForeignKey("IdPojazdu");

                    b.HasOne("Transit.Domain.Entities.Siec.WariantTrasy", "Wariant")
                        .WithMany("Realizacje")
                        .HasForeignKey("IdWariantu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kierowca");

                    b.Navigation("Pojazd");

                    b.Navigation("Wariant");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Rozklady.RozkladJazdy", b =>
                {
                    b.HasOne("Transit.Domain.Entities.Slowniki.TypDnia", "TypDnia")
                        .WithMany("Rozklady")
                        .HasForeignKey("IdTypuDnia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transit.Domain.Entities.Siec.WariantTrasy", "Wariant")
                        .WithMany("Rozklady")
                        .HasForeignKey("IdWariantu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypDnia");

                    b.Navigation("Wariant");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Siec.Przystanek", b =>
                {
                    b.HasOne("Transit.Domain.Entities.Slowniki.Dzielnica", "Dzielnica")
                        .WithMany("Przystanki")
                        .HasForeignKey("IdDzielnicy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dzielnica");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Siec.PrzystanekWariantu", b =>
                {
                    b.HasOne("Transit.Domain.Entities.Siec.Przystanek", "Przystanek")
                        .WithMany("PrzystankiWariantu")
                        .HasForeignKey("IdPrzystanku")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transit.Domain.Entities.Siec.WariantTrasy", "Wariant")
                        .WithMany("PrzystankiWariantu")
                        .HasForeignKey("IdWariantu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Przystanek");

                    b.Navigation("Wariant");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Siec.WariantTrasy", b =>
                {
                    b.HasOne("Transit.Domain.Entities.Siec.Linia", "Linia")
                        .WithMany("Warianty")
                        .HasForeignKey("IdLinii")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linia");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Pasazerowie.KontrolaWPojedzie", b =>
                {
                    b.Navigation("Mandaty");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Pasazerowie.Pasazer", b =>
                {
                    b.Navigation("Bilety");

                    b.Navigation("Mandaty");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Personel.Kierowca", b =>
                {
                    b.Navigation("Badania");

                    b.Navigation("Grafiki");

                    b.Navigation("Realizacje");

                    b.Navigation("Uprawnienia");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Personel.Kontroler", b =>
                {
                    b.Navigation("Kontrole");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Pojazdy.ModelPojazdu", b =>
                {
                    b.Navigation("Pojazdy");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Pojazdy.Pojazd", b =>
                {
                    b.Navigation("Grafiki");

                    b.Navigation("Przeglady");

                    b.Navigation("Realizacje");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Pojazdy.ProducentPojazdu", b =>
                {
                    b.Navigation("Modele");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Rozklady.OdjazdPlanowy", b =>
                {
                    b.Navigation("Dzienniki");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Rozklady.RealizacjaKursu", b =>
                {
                    b.Navigation("Dzienniki");

                    b.Navigation("Kontrole");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Rozklady.RozkladJazdy", b =>
                {
                    b.Navigation("Odjazdy");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Siec.Linia", b =>
                {
                    b.Navigation("Warianty");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Siec.Przystanek", b =>
                {
                    b.Navigation("PrzystankiWariantu");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Siec.PrzystanekWariantu", b =>
                {
                    b.Navigation("Odjazdy");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Siec.WariantTrasy", b =>
                {
                    b.Navigation("PrzystankiWariantu");

                    b.Navigation("Realizacje");

                    b.Navigation("Rozklady");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Slowniki.Dzielnica", b =>
                {
                    b.Navigation("Przystanki");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Slowniki.KategoriaOplaty", b =>
                {
                    b.Navigation("Bilety");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Slowniki.TypDnia", b =>
                {
                    b.Navigation("Rozklady");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Slowniki.TypPrzegladu", b =>
                {
                    b.Navigation("Przeglady");
                });

            modelBuilder.Entity("Transit.Domain.Entities.Slowniki.UprawnienieKategorii", b =>
                {
                    b.Navigation("UprawnieniKierowcow");
                });
#pragma warning restore 612, 618
        }
    }
}
